/**
 * Prefecture guide content for /blog. Authored by hand (no API), kept to
 * stable, well-established facts; each links to JNTO (japan.travel) as the
 * authoritative source. `full:true` = a richer bespoke .html already exists
 * (the build script lists it in the index but does NOT overwrite it).
 *
 * Consumed by scripts/build-guides.mjs → emits blog/<slug>.html + index.
 * Regions match prefectures.html: hokkaido / tohoku / kanto / chubu /
 * kansai / chugoku / shikoku / kyushu-okinawa.
 *
 * Enriched fields (2026-06-02, 3rd pass) on non-full entries:
 *   getting  — how to reach it (general, accurate)
 *   when     — best time to visit
 *   word     — a real prefecture-linked Japanese word (learning hook) {jp,ro,en}
 *   related  — 2-3 related prefecture slugs for internal linking (SEO)
 *   tip      — one practical traveler tip
 */
export const REGION_LABELS = {
  hokkaido: "HOKKAIDŌ",
  tohoku: "TŌHOKU",
  kanto: "KANTŌ",
  chubu: "CHŪBU",
  kansai: "KANSAI",
  chugoku: "CHŪGOKU",
  shikoku: "SHIKOKU",
  "kyushu-okinawa": "KYŪSHŪ / OKINAWA",
};

const P = {
  recommend: { jp: "おすすめは何ですか？", ro: "Osusume wa nan desu ka?", en: "What do you recommend?" },
  howmuch:   { jp: "いくらですか？", ro: "Ikura desu ka?", en: "How much is it?" },
  delicious: { jp: "おいしいです！", ro: "Oishii desu!", en: "It's delicious!" },
  beautiful: { jp: "きれいですね。", ro: "Kirei desu ne.", en: "It's beautiful, isn't it?" },
  where:     { jp: "駅はどこですか？", ro: "Eki wa doko desu ka?", en: "Where is the station?" },
  menu:      { jp: "英語のメニューはありますか？", ro: "Eigo no menyū wa arimasu ka?", en: "Do you have an English menu?" },
  this:      { jp: "これをください。", ro: "Kore o kudasai.", en: "I'll have this, please." },
  thanks:    { jp: "ありがとうございます。", ro: "Arigatō gozaimasu.", en: "Thank you very much." },
};

export const GUIDES = [
  // ── HOKKAIDŌ ──
  { slug:"hokkaido", kanji:"北海道", romaji:"Hokkaido", region:"hokkaido", full:true,
    blurb:"Powder snow, onsen, seafood, and wide-open nature." },

  // ── TŌHOKU ──
  { slug:"aomori", kanji:"青森", romaji:"Aomori", region:"tohoku",
    lede:"Japan's apple country at the northern tip of Honshu, famous for the explosive Nebuta summer festival.",
    intro:"Aomori sits where Honshu meets the sea toward Hokkaido. It's known for crisp apples, fresh seafood, and the Jōmon-era Sannai-Maruyama ruins, plus some of the deepest snow in the country.",
    see:["Nebuta Matsuri — giant illuminated floats every August","Hirosaki Castle and its famous cherry blossoms","Oirase Gorge and Lake Towada","Sannai-Maruyama — a major prehistoric site (UNESCO)"],
    eat:"Try the apples, scallops, and Ōma bluefin tuna.", phrase:P.delicious,
    getting:"About 3 hours from Tokyo by Tōhoku Shinkansen to Shin-Aomori.",
    when:"Early August for the Nebuta Matsuri; late April–May for Hirosaki's cherry blossoms.",
    word:{jp:"ねぶた", ro:"nebuta", en:"the giant illuminated festival floats"},
    related:["iwate","akita"], tip:"Book accommodation months ahead if you visit during Nebuta (Aug 2–7)." },
  { slug:"iwate", kanji:"岩手", romaji:"Iwate", region:"tohoku",
    lede:"A vast, rugged prefecture of temples, coastline, and cold-soba traditions.",
    intro:"Iwate is the second-largest prefecture by area and one of the least crowded. Its highlight is Hiraizumi, a UNESCO World Heritage site of Pure Land Buddhist temples and gardens.",
    see:["Chūson-ji and Mōtsū-ji temples in Hiraizumi (UNESCO)","Geibikei and Genbikei gorges","The dramatic Sanriku coast","Morioka's historic streets"],
    eat:"Morioka is famous for three noodles: wanko-soba, reimen, and jajamen.", phrase:P.recommend,
    getting:"Morioka is ~2h10m from Tokyo by Tōhoku Shinkansen.",
    when:"Spring to autumn for hiking and the coast; summer for the wanko-soba challenge.",
    word:{jp:"わんこそば", ro:"wanko-soba", en:"all-you-can-eat bite-size soba"},
    related:["aomori","miyagi"], tip:"At wanko-soba restaurants, put the lid on your bowl to signal you're full — otherwise refills keep coming." },
  { slug:"miyagi", kanji:"宮城", romaji:"Miyagi", region:"tohoku",
    lede:"Home to lively Sendai and one of Japan's 'three great views' at Matsushima Bay.",
    intro:"Miyagi centers on Sendai, the largest city in Tōhoku, founded by the legendary lord Date Masamune. The pine-dotted islands of Matsushima Bay are a classic scenic spot.",
    see:["Matsushima Bay — pine-covered islets","Sendai's Zuihōden mausoleum","Aoba Castle ruins","Naruko Onsen hot springs"],
    eat:"Sendai is famous for grilled beef tongue (gyūtan) and zunda (sweet edamame paste).", phrase:P.recommend,
    getting:"Sendai is ~1h30m from Tokyo by Tōhoku Shinkansen — the easiest Tōhoku city to reach.",
    when:"Year-round; Matsushima is lovely in autumn, and Sendai's Tanabata festival is in August.",
    word:{jp:"牛タン", ro:"gyū-tan", en:"grilled beef tongue, a Sendai specialty"},
    related:["iwate","fukushima"], tip:"Take a short cruise around Matsushima Bay to see the islands from the water." },
  { slug:"akita", kanji:"秋田", romaji:"Akita", region:"tohoku",
    lede:"Deep snow, rice and sake country, and the fierce Namahage folk tradition.",
    intro:"Akita is rural, snowy, and proud of its traditions — from the Kantō pole-lantern festival to the Namahage ogre-visitors of the Oga Peninsula. It's also famed for beautiful rice and the Akita dog.",
    see:["Kakunodate — preserved samurai district","Lake Tazawa, Japan's deepest lake","Nyūtō Onsen hot springs","Oga Peninsula and the Namahage"],
    eat:"Try kiritanpo (mashed-rice skewers) hot pot and local sake.", phrase:P.beautiful,
    getting:"Akita is ~3h40m from Tokyo by Akita Shinkansen.",
    when:"Spring for Kakunodate's weeping cherries; winter for snow and onsen.",
    word:{jp:"なまはげ", ro:"namahage", en:"the New Year ogre-visitors of the Oga Peninsula"},
    related:["aomori","yamagata"], tip:"The Akita dog (Akita-inu) hails from here — you'll find friendly meet-and-greet spots." },
  { slug:"yamagata", kanji:"山形", romaji:"Yamagata", region:"tohoku",
    lede:"Mountain temples, cherries, and snow monsters on Mount Zaō.",
    intro:"Yamagata blends spiritual mountains and orchard valleys. The cliffside Yamadera temple inspired the poet Bashō, and winter brings the famous 'snow monster' frost-covered trees of Zaō.",
    see:["Yamadera (Risshaku-ji) cliff temple","Zaō Onsen and its winter 'snow monsters'","The Dewa Sanzan sacred mountains","Ginzan Onsen's nostalgic streets"],
    eat:"Yamagata is Japan's cherry capital; also try imoni (taro hot pot).", phrase:P.beautiful,
    getting:"Yamagata is ~2h30m from Tokyo by Yamagata Shinkansen.",
    when:"June–July for cherries; February for Zaō's snow monsters lit up at night.",
    word:{jp:"さくらんぼ", ro:"sakuranbo", en:"cherries — Yamagata grows most of Japan's"},
    related:["akita","fukushima"], tip:"Climb the 1,000 steps to Yamadera early to beat the crowds and the heat." },
  { slug:"fukushima", kanji:"福島", romaji:"Fukushima", region:"tohoku",
    lede:"Samurai history, hot springs, and fruit orchards in a large, scenic prefecture.",
    intro:"Fukushima offers the well-preserved samurai town of Aizu-Wakamatsu, thatched post-town villages, and excellent peaches and sake. The Aizu region is especially rich in history.",
    see:["Tsuruga Castle in Aizu-Wakamatsu","Ouchi-juku — thatched-roof post town","Goshiki-numa volcanic lakes","Spa Resort Hawaiians"],
    eat:"Kitakata ramen and local sake are regional stars.", phrase:P.recommend,
    getting:"Kōriyama/Fukushima are ~1h20m–1h40m from Tokyo by Tōhoku Shinkansen.",
    when:"Summer for peaches; autumn for foliage around the Aizu lakes.",
    word:{jp:"会津", ro:"Aizu", en:"the historic samurai region of western Fukushima"},
    related:["miyagi","yamagata"], tip:"At Ouchi-juku, try the negi-soba — eaten using a whole leek as a 'chopstick'." },

  // ── KANTŌ ──
  { slug:"ibaraki", kanji:"茨城", romaji:"Ibaraki", region:"kanto",
    lede:"Seasonal flower parks, a giant Buddha, and natto just north of Tokyo.",
    intro:"Ibaraki is an easy escape from the capital. Hitachi Seaside Park bursts with blue nemophila in spring and red kochia in autumn, and Ushiku hosts one of the world's tallest bronze statues.",
    see:["Hitachi Seaside Park flower fields","Ushiku Daibutsu (giant Buddha)","Kairaku-en — one of Japan's three great gardens","Fukuroda Falls"],
    eat:"Mito is the home of natto (fermented soybeans); also fresh anglerfish (ankō).", phrase:P.beautiful,
    getting:"Mito is ~1h15m from Tokyo by limited express; Hitachi Seaside Park by bus from Katsuta.",
    when:"Late April–May for blue nemophila; October for the crimson kochia hills.",
    word:{jp:"納豆", ro:"nattō", en:"sticky fermented soybeans — Mito is famous for them"},
    related:["tochigi","chiba"], tip:"Time your trip to Hitachi Seaside Park with the nemophila or kochia peak — check the bloom calendar." },
  { slug:"tochigi", kanji:"栃木", romaji:"Tochigi", region:"kanto",
    lede:"Home to the ornate shrines and waterfalls of Nikkō.",
    intro:"Tochigi's crown jewel is Nikkō, where lavish Edo-era shrines sit among cedar forests, lakes, and waterfalls. It's one of the most popular day trips from Tokyo.",
    see:["Nikkō Tōshō-gū shrine (UNESCO)","Kegon Falls and Lake Chūzenji","Edo Wonderland theme park","Ashikaga Flower Park's wisteria"],
    eat:"Utsunomiya is Japan's gyōza (dumpling) capital.", phrase:P.recommend,
    getting:"Nikkō is ~2h from Tokyo (Tōbu line from Asakusa, or shinkansen + transfer).",
    when:"Late April–May for wisteria; October–November for Nikkō's spectacular foliage.",
    word:{jp:"餃子", ro:"gyōza", en:"pan-fried dumplings — Utsunomiya's specialty"},
    related:["ibaraki","gunma"], tip:"Nikkō's autumn colours draw huge crowds — start early and consider a weekday." },
  { slug:"gunma", kanji:"群馬", romaji:"Gunma", region:"kanto",
    lede:"Famous hot-spring resorts and a UNESCO silk-mill heritage.",
    intro:"Landlocked Gunma is onsen country. Kusatsu is one of Japan's most celebrated hot-spring towns, and the Tomioka Silk Mill marks the start of Japan's modern industry.",
    see:["Kusatsu Onsen and its yubatake hot-water field","Ikaho Onsen's stone steps","Tomioka Silk Mill (UNESCO)","Mount Haruna and Lake Haruna"],
    eat:"Try Mizusawa udon and local konnyaku.", phrase:P.where,
    getting:"Takasaki is ~50 min from Tokyo by shinkansen; onsen towns by bus/local line.",
    when:"Any season — onsen are especially welcome in cold months.",
    word:{jp:"温泉", ro:"onsen", en:"hot spring — Gunma has Japan's most famous ones"},
    related:["tochigi","niigata"], tip:"Catch the 'yumomi' hot-water-stirring performance at Kusatsu." },
  { slug:"saitama", kanji:"埼玉", romaji:"Saitama", region:"kanto",
    lede:"A little Edo at Kawagoe, plus bonsai and bustling suburbs.",
    intro:"Saitama wraps around the north of Tokyo. Kawagoe ('Little Edo') preserves clay-walled merchant streets and a wooden bell tower, an easy and charming half-day trip.",
    see:["Kawagoe's Kurazukuri warehouse street and Bell Tower","Hitsujiyama Park's shibazakura (pink moss)","Omiya Bonsai Village","Railway Museum in Omiya"],
    eat:"Kawagoe is known for sweet-potato treats.", phrase:P.this,
    getting:"Kawagoe is ~30–45 min from central Tokyo by train (Tōbu/Seibu/JR).",
    when:"April for shibazakura; year-round for Kawagoe's old streets.",
    word:{jp:"小江戸", ro:"ko-edo", en:"'Little Edo' — Kawagoe's nickname"},
    related:["tokyo","gunma"], tip:"Kawagoe makes a perfect half-day trip when Tokyo feels too busy." },
  { slug:"chiba", kanji:"千葉", romaji:"Chiba", region:"kanto",
    lede:"Tokyo's seaside neighbor — the airport gateway, beaches, and a famous temple.",
    intro:"Chiba is where most visitors first land (Narita Airport) and home to Tokyo Disney Resort (actually in Urayasu). Beyond that lie surf beaches, the Bōsō Peninsula, and the grand Narita-san temple.",
    see:["Narita-san Shinshō-ji temple","Tokyo Disney Resort (Urayasu)","Nokogiriyama and its cliff Buddha","Kujūkuri beaches for surfing"],
    eat:"Fresh seafood and peanuts are local specialties.", phrase:P.where,
    getting:"Narita Airport is in Chiba; central Chiba ~40 min from Tokyo by train.",
    when:"Summer for beaches and surfing; spring for temple visits.",
    word:{jp:"成田山", ro:"Narita-san", en:"the major temple near Narita Airport"},
    related:["tokyo","ibaraki"], tip:"Long layover at Narita? Narita-san temple is a quick, worthwhile trip from the airport." },
  { slug:"tokyo", kanji:"東京", romaji:"Tokyo", region:"kanto", full:true,
    blurb:"Neon, temples, and the world's best trains." },
  { slug:"kanagawa", kanji:"神奈川", romaji:"Kanagawa", region:"kanto",
    lede:"The Great Buddha of Kamakura, the port city of Yokohama, and Hakone's hot springs.",
    intro:"Just south of Tokyo, Kanagawa packs in the seaside temple-town of Kamakura, cosmopolitan Yokohama with its big Chinatown, and the onsen-and-views resort of Hakone with Mount Fuji on clear days.",
    see:["The Great Buddha (Daibutsu) of Kamakura","Hakone hot springs and Lake Ashi","Yokohama Minato Mirai and Chinatown","Enoshima island"],
    eat:"Yokohama Chinatown and shirasu (whitebait) near Enoshima.", phrase:P.beautiful,
    getting:"Yokohama ~30 min, Kamakura ~1h, Hakone ~1h25m from Tokyo by train.",
    when:"Clear winter days give the best Mount Fuji views from Hakone.",
    word:{jp:"大仏", ro:"daibutsu", en:"Great Buddha — Kamakura's iconic bronze statue"},
    related:["tokyo","shizuoka"], tip:"The Hakone Free Pass covers the loop of trains, cablecars, and pirate ship around Lake Ashi." },

  // ── CHŪBU ──
  { slug:"niigata", kanji:"新潟", romaji:"Niigata", region:"chubu",
    lede:"Rice, sake, and snow on the Sea of Japan coast.",
    intro:"Niigata produces some of Japan's best rice and sake, has world-class ski snow, and faces Sado Island across the sea. It's a quick shinkansen ride from Tokyo.",
    see:["Sado Island and its gold-mine history","Echigo-Tsumari open-air art fields","Ski resorts around Yuzawa","Local sake breweries"],
    eat:"Koshihikari rice, sake, and hegi-soba.", phrase:P.recommend,
    getting:"Niigata is ~2h, Echigo-Yuzawa ~1h15m from Tokyo by Jōetsu Shinkansen.",
    when:"Winter for skiing; summer for the Echigo-Tsumari art triennale years.",
    word:{jp:"日本酒", ro:"nihonshu", en:"sake — Niigata is one of Japan's top regions for it"},
    related:["nagano","toyama"], tip:"At Echigo-Yuzawa Station, the 'ponshukan' lets you taste dozens of local sakes by coin." },
  { slug:"toyama", kanji:"富山", romaji:"Toyama", region:"chubu",
    lede:"Towering snow walls in the Alps and glassy bays of firefly squid.",
    intro:"Toyama faces the sea below the Northern Japan Alps. The Tateyama Kurobe Alpine Route carves through corridors of snow up to 20 m high in spring, an unforgettable journey.",
    see:["Tateyama Kurobe Alpine Route and the snow walls","Kurobe Gorge railway","Gokayama's thatched gasshō villages (UNESCO)","Zuiryū-ji temple in Takaoka"],
    eat:"Firefly squid (hotaru-ika) and white shrimp.", phrase:P.beautiful,
    getting:"Toyama is ~2h10m from Tokyo by Hokuriku Shinkansen.",
    when:"Mid-April to June for the snow walls; spring for firefly squid season.",
    word:{jp:"雪の大谷", ro:"yuki-no-ōtani", en:"the towering snow-wall corridor on the Alpine Route"},
    related:["ishikawa","nagano"], tip:"The Alpine Route's snow walls open mid-April — it's closed in deep winter." },
  { slug:"ishikawa", kanji:"石川", romaji:"Ishikawa", region:"chubu",
    lede:"Kanazawa's gardens and gold leaf, plus the rugged Noto Peninsula.",
    intro:"Ishikawa centers on Kanazawa, a refined castle town that escaped wartime bombing. Kenroku-en is celebrated as one of Japan's three great landscape gardens.",
    see:["Kenroku-en garden","Higashi Chaya geisha district","Kanazawa Castle and the 21st Century Museum","Noto Peninsula coastline"],
    eat:"Fresh seafood, gold-leaf ice cream, and Kaga cuisine.", phrase:P.beautiful,
    getting:"Kanazawa is ~2h30m from Tokyo by Hokuriku Shinkansen.",
    when:"Any season; Kenroku-en is magical with winter 'yukitsuri' rope supports.",
    word:{jp:"金箔", ro:"kinpaku", en:"gold leaf — Kanazawa makes most of Japan's"},
    related:["toyama","fukui"], tip:"Try gold-leaf-topped soft-serve ice cream in the Higashi Chaya district." },
  { slug:"fukui", kanji:"福井", romaji:"Fukui", region:"chubu",
    lede:"Dinosaurs, dramatic cliffs, and a great Zen temple.",
    intro:"Quiet Fukui surprises visitors with Japan's top dinosaur museum, the meditative Eihei-ji temple, and the wave-cut cliffs of Tōjinbō.",
    see:["Fukui Prefectural Dinosaur Museum","Eihei-ji Zen temple","Tōjinbō cliffs","Maruoka Castle"],
    eat:"Echizen crab in winter and sauce-katsudon.", phrase:P.recommend,
    getting:"Fukui is reachable via the Hokuriku Shinkansen (extended to Tsuruga in 2024).",
    when:"November–March for Echizen crab; spring/autumn for temples and cliffs.",
    word:{jp:"恐竜", ro:"kyōryū", en:"dinosaur — Fukui is Japan's dinosaur capital"},
    related:["ishikawa","shiga"], tip:"Eihei-ji offers a glimpse of working Zen monastic life — visit respectfully and quietly." },
  { slug:"yamanashi", kanji:"山梨", romaji:"Yamanashi", region:"chubu",
    lede:"Mount Fuji's lakes, vineyards, and Japan's wine country.",
    intro:"Yamanashi offers the classic Mount Fuji views from the Fuji Five Lakes, plus Japan's leading wine region around Kōfu. It's a popular nature escape from Tokyo.",
    see:["Lake Kawaguchi and Fuji views","Chūreitō Pagoda viewpoint","Kōfu Basin vineyards and wineries","Shōsenkyō Gorge"],
    eat:"Hōtō (flat-noodle miso hot pot) and grapes/wine.", phrase:P.beautiful,
    getting:"Lake Kawaguchi is ~2h from Tokyo by bus or train (via Ōtsuki).",
    when:"Clear autumn/winter mornings for the sharpest Fuji views; autumn for grapes.",
    word:{jp:"富士山", ro:"Fuji-san", en:"Mount Fuji — best viewed from Yamanashi's lakes"},
    related:["shizuoka","nagano"], tip:"The Chūreitō Pagoda framed with Fuji and cherry blossoms is the classic postcard shot." },
  { slug:"nagano", kanji:"長野", romaji:"Nagano", region:"chubu",
    lede:"Alpine peaks, the great Zenkō-ji temple, and snow monkeys in hot springs.",
    intro:"Nagano hosted the 1998 Winter Olympics and is Japan's mountain heartland. Visit the ancient Zenkō-ji, the bathing snow monkeys of Jigokudani, and the post towns of the Kiso Valley.",
    see:["Zenkō-ji temple","Jigokudani snow monkey park","Matsumoto Castle","Kiso Valley post towns (Tsumago/Magome)"],
    eat:"Shinshu soba and oyaki dumplings.", phrase:P.beautiful,
    getting:"Nagano city is ~1h30m from Tokyo by Hokuriku Shinkansen.",
    when:"Winter for snow monkeys in the steam; summer for cool alpine hiking.",
    word:{jp:"そば", ro:"soba", en:"buckwheat noodles — Shinshu (Nagano) is famous for them"},
    related:["niigata","gifu"], tip:"The snow monkeys are a 30-min uphill walk from the bus stop — wear proper footwear in winter." },
  { slug:"gifu", kanji:"岐阜", romaji:"Gifu", region:"chubu",
    lede:"Thatched mountain villages and the riverside old town of Takayama.",
    intro:"Gifu reaches deep into the Alps. Shirakawa-gō's steep thatched farmhouses are a UNESCO icon, and Takayama preserves a beautifully intact merchant district.",
    see:["Shirakawa-gō gasshō-zukuri village (UNESCO)","Takayama old town","Gujō Hachiman and its summer dance","Gifu Castle and cormorant fishing"],
    eat:"Hida beef is a prized local specialty.", phrase:P.delicious,
    getting:"Takayama is ~2h20m from Nagoya by limited express; Shirakawa-gō by bus.",
    when:"Winter for snow-covered thatched roofs (and light-up nights); spring/autumn for Takayama festivals.",
    word:{jp:"合掌造り", ro:"gasshō-zukuri", en:"the steep thatched farmhouse style of Shirakawa-gō"},
    related:["nagano","toyama"], tip:"Shirakawa-gō's winter evening illuminations are limited and need advance reservation." },
  { slug:"shizuoka", kanji:"静岡", romaji:"Shizuoka", region:"chubu",
    lede:"Mount Fuji, green tea fields, and the coastal Izu Peninsula.",
    intro:"Shizuoka stretches along the Pacific beneath Mount Fuji. It grows most of Japan's green tea, and the Izu Peninsula is dotted with hot springs and beaches.",
    see:["Mount Fuji views and the 5th Station","Miho-no-Matsubara pine grove","Izu Peninsula onsen towns","Sunpu Castle in Shizuoka City"],
    eat:"Green tea everything, plus seafood and Fuji-noodles.", phrase:P.beautiful,
    getting:"Shizuoka City is ~1h from Tokyo by Tōkaidō Shinkansen.",
    when:"Spring–early summer for tea fields; clear winter days for Fuji.",
    word:{jp:"お茶", ro:"o-cha", en:"green tea — Shizuoka is Japan's biggest producer"},
    related:["yamanashi","kanagawa"], tip:"The Izu Peninsula is a relaxed onsen escape that's easy to pair with a Fuji view." },
  { slug:"aichi", kanji:"愛知", romaji:"Aichi", region:"chubu",
    lede:"Nagoya's castle and industry, plus samurai-era history.",
    intro:"Aichi centers on Nagoya, Japan's fourth-largest city and an industrial powerhouse (home of Toyota). It has a reconstructed castle, a major shrine, and a hearty local food culture.",
    see:["Nagoya Castle","Atsuta Shrine","Toyota Commemorative Museum","Inuyama Castle"],
    eat:"Nagoya 'meshi': miso-katsu, hitsumabushi eel, and tebasaki wings.", phrase:P.recommend,
    getting:"Nagoya is ~1h40m from Tokyo and ~50 min from Kyoto by Tōkaidō Shinkansen.",
    when:"Year-round; a handy hub between Tokyo and Kyoto.",
    word:{jp:"味噌カツ", ro:"miso-katsu", en:"pork cutlet with rich red-miso sauce, a Nagoya classic"},
    related:["gifu","mie"], tip:"Nagoya makes a good base for day trips to Gifu's Takayama or Mie's Ise." },

  // ── KANSAI ──
  { slug:"mie", kanji:"三重", romaji:"Mie", region:"kansai",
    lede:"Japan's holiest shrine at Ise and the pearl-diving Ama tradition.",
    intro:"Mie is home to Ise Jingū, the most sacred Shintō shrine, set in ancient forest. The coast is known for pearls and the free-diving Ama women.",
    see:["Ise Jingū grand shrine","Meoto Iwa (the Wedded Rocks)","Toba pearl islands","Iga-Ueno ninja sites"],
    eat:"Ise-Shima seafood and prized Matsusaka beef.", phrase:P.recommend,
    getting:"Ise is ~1h20m from Nagoya by limited express; ~2h from Osaka.",
    when:"Any season; the shrine is especially atmospheric in early morning.",
    word:{jp:"伊勢神宮", ro:"Ise Jingū", en:"Japan's most sacred Shintō shrine"},
    related:["aichi","nara"], tip:"Visit the Outer Shrine (Gekū) before the Inner Shrine (Naikū) — the traditional order." },
  { slug:"shiga", kanji:"滋賀", romaji:"Shiga", region:"kansai",
    lede:"Wrapped around Japan's largest lake, with a stunning castle.",
    intro:"Shiga is defined by Lake Biwa, the country's biggest freshwater lake. Hikone Castle is one of only a handful of original castles still standing.",
    see:["Lake Biwa","Hikone Castle (original keep)","Enryaku-ji temple on Mount Hiei (UNESCO)","Miho Museum"],
    eat:"Ōmi beef and funazushi (an ancient fermented sushi).", phrase:P.beautiful,
    getting:"Ōtsu/Hikone are ~10–50 min from Kyoto by train.",
    when:"Any season; an easy add-on to a Kyoto trip.",
    word:{jp:"琵琶湖", ro:"Biwa-ko", en:"Lake Biwa, Japan's largest lake"},
    related:["kyoto","fukui"], tip:"Hikone Castle is a genuine original keep — rarer than most 'castles' you'll see in Japan." },
  { slug:"kyoto", kanji:"京都", romaji:"Kyoto", region:"kansai", full:true,
    blurb:"Temples, tea, bamboo — the cultural heart." },
  { slug:"osaka", kanji:"大阪", romaji:"Osaka", region:"kansai", full:true,
    blurb:"The friendly food capital. Eat until you drop." },
  { slug:"hyogo", kanji:"兵庫", romaji:"Hyogo", region:"kansai",
    lede:"Japan's most beautiful castle at Himeji and the port city of Kobe.",
    intro:"Hyōgo runs from the Sea of Japan to the Inland Sea. Himeji Castle is the country's finest surviving fortress, and cosmopolitan Kobe is famous worldwide for its beef.",
    see:["Himeji Castle (UNESCO)","Kobe harbor and Mount Rokkō","Arima Onsen","Kinosaki Onsen town"],
    eat:"Kobe beef and Akashi octopus.", phrase:P.beautiful,
    getting:"Kobe is ~30 min and Himeji ~40 min from Osaka by train.",
    when:"Any season; cherry blossoms frame Himeji Castle beautifully in early April.",
    word:{jp:"姫路城", ro:"Himeji-jō", en:"Himeji Castle, the 'White Heron' castle"},
    related:["osaka","kyoto"], tip:"Himeji Castle is an easy day trip from Osaka or Kyoto by shinkansen." },
  { slug:"nara", kanji:"奈良", romaji:"Nara", region:"kansai",
    lede:"Japan's first capital — a giant Buddha and free-roaming deer.",
    intro:"Nara was the capital in the 8th century and preserves some of the country's oldest temples. Wild deer roam its central park, bowing for crackers.",
    see:["Tōdai-ji and its Great Buddha (UNESCO)","Nara Park's deer","Kasuga Taisha shrine","Hōryū-ji, among the world's oldest wooden buildings"],
    eat:"Kakinoha-zushi (persimmon-leaf sushi) and mochi.", phrase:P.beautiful,
    getting:"Nara is ~45 min from both Kyoto and Osaka by train.",
    when:"Any season; an easy day trip from Kyoto or Osaka.",
    word:{jp:"鹿", ro:"shika", en:"deer — Nara Park's free-roaming residents"},
    related:["kyoto","osaka"], tip:"The deer crackers (shika-senbei) are sold around the park; the deer will bow for them." },
  { slug:"wakayama", kanji:"和歌山", romaji:"Wakayama", region:"kansai",
    lede:"Sacred pilgrimage mountains and dramatic coastal hot springs.",
    intro:"Wakayama holds the spiritual heart of Kōyasan (Mount Kōya) and the Kumano Kodō pilgrimage routes, both UNESCO sites, plus a rugged southern coast.",
    see:["Kōyasan temple town and Okunoin","Kumano Kodō pilgrimage trails (UNESCO)","Nachi Falls and shrine","Shirahama beach and onsen"],
    eat:"Wakayama ramen and umeboshi (pickled plums).", phrase:P.recommend,
    getting:"Kōyasan is ~2h from Osaka by train and cablecar.",
    when:"Spring–autumn for hiking the Kumano Kodō; any season for Kōyasan's calm.",
    word:{jp:"高野山", ro:"Kōyasan", en:"Mount Kōya, a sacred Buddhist monastery town"},
    related:["nara","mie"], tip:"Stay overnight in a Kōyasan temple lodging (shukubō) to join morning prayers." },

  // ── CHŪGOKU ──
  { slug:"tottori", kanji:"鳥取", romaji:"Tottori", region:"chugoku",
    lede:"Japan's famous sand dunes on the Sea of Japan.",
    intro:"Tottori is the least-populous prefecture, best known for the vast Tottori Sand Dunes and a quirky sand sculpture museum. It's also manga country.",
    see:["Tottori Sand Dunes","The Sand Museum","Mount Daisen","Mizuki Shigeru Road (yōkai manga)"],
    eat:"Snow crab in winter.", phrase:P.beautiful,
    getting:"Tottori is reached by limited express from Okayama or Osaka.",
    when:"Winter for snow crab; spring–autumn for the dunes (summer sand gets very hot).",
    word:{jp:"砂丘", ro:"sakyū", en:"sand dunes — Tottori's signature landscape"},
    related:["shimane","okayama"], tip:"You can ride a camel or sandboard on the dunes; go near sunset to avoid midday heat." },
  { slug:"shimane", kanji:"島根", romaji:"Shimane", region:"chugoku",
    lede:"Home to Izumo Taisha, one of Japan's oldest and grandest shrines.",
    intro:"Shimane is steeped in mythology. Izumo Taisha is among the most important shrines in the country, and the silver-mining town of Iwami Ginzan is a UNESCO site.",
    see:["Izumo Taisha grand shrine","Matsue Castle (original keep)","Iwami Ginzan silver mine (UNESCO)","Adachi Museum of Art garden"],
    eat:"Izumo soba and Shijimi-clam miso soup.", phrase:P.beautiful,
    getting:"Izumo/Matsue are reached by air from Tokyo or by limited express from Okayama.",
    when:"Any season; October is the mythical 'month of the gods' at Izumo.",
    word:{jp:"縁結び", ro:"enmusubi", en:"matchmaking / forging bonds — Izumo Taisha's specialty"},
    related:["tottori","yamaguchi"], tip:"At Izumo Taisha, worshippers clap four times (not the usual two) — twice for themselves, twice for a partner." },
  { slug:"okayama", kanji:"岡山", romaji:"Okayama", region:"chugoku",
    lede:"A great garden, a 'crow castle', and the canal town of Kurashiki.",
    intro:"Sunny Okayama is home to Kōraku-en, one of Japan's three great gardens, and the picturesque Bikan canal district of Kurashiki. It's linked to the Momotarō peach-boy legend.",
    see:["Kōraku-en garden and Okayama Castle","Kurashiki Bikan historical quarter","Washūzan views of the Seto bridges","Kibitsu Shrine"],
    eat:"Peaches, muscat grapes, and barazushi.", phrase:P.beautiful,
    getting:"Okayama is ~3h15m from Tokyo and ~45 min from Osaka by shinkansen.",
    when:"Summer for peaches and muscat grapes; any season for the gardens.",
    word:{jp:"桃太郎", ro:"Momotarō", en:"the Peach Boy folktale tied to Okayama"},
    related:["hiroshima","kagawa"], tip:"Okayama is the gateway to Shikoku's art islands via the Seto-Ōhashi bridge." },
  { slug:"hiroshima", kanji:"広島", romaji:"Hiroshima", region:"chugoku",
    lede:"A moving peace memorial and the floating torii of Miyajima.",
    intro:"Hiroshima pairs profound history with great beauty. The Peace Memorial Park commemorates 1945, while nearby Miyajima's Itsukushima Shrine seems to float at high tide.",
    see:["Peace Memorial Park and the A-Bomb Dome (UNESCO)","Itsukushima Shrine on Miyajima (UNESCO)","Hiroshima Castle","Shukkei-en garden"],
    eat:"Hiroshima-style okonomiyaki (layered) and oysters.", phrase:P.recommend,
    getting:"Hiroshima is ~4h from Tokyo and ~1h25m from Osaka by shinkansen.",
    when:"Any season; check the tide table to see Miyajima's torii 'floating'.",
    word:{jp:"平和", ro:"heiwa", en:"peace — the message of Hiroshima's memorial"},
    related:["okayama","yamaguchi"], tip:"Time your Miyajima visit with high tide for the floating torii, low tide to walk out to it." },
  { slug:"yamaguchi", kanji:"山口", romaji:"Yamaguchi", region:"chugoku",
    lede:"A spectacular five-arched bridge and a vivid vermilion shrine.",
    intro:"At Honshu's western tip, Yamaguchi offers the elegant Kintai-kyō bridge, the seaside fox shrine of Motonosumi, and the limestone caves of Akiyoshidai.",
    see:["Kintai-kyō wooden arched bridge","Motonosumi Inari Shrine's red gates","Akiyoshidō cave and plateau","Tsunoshima Bridge"],
    eat:"Fugu (pufferfish) is the local delicacy in Shimonoseki.", phrase:P.beautiful,
    getting:"Shin-Yamaguchi is on the Sanyō Shinkansen line; Iwakuni near Hiroshima.",
    when:"Spring/autumn for the Kintai-kyō bridge with blossoms or foliage.",
    word:{jp:"ふぐ", ro:"fugu", en:"pufferfish — Shimonoseki's famous (and licensed) delicacy"},
    related:["hiroshima","shimane"], tip:"Fugu is prepared only by licensed chefs — eat it at a reputable Shimonoseki restaurant." },

  // ── SHIKOKU ──
  { slug:"tokushima", kanji:"徳島", romaji:"Tokushima", region:"shikoku",
    lede:"Roaring whirlpools and the electric Awa Odori dance.",
    intro:"Tokushima is famous for the tidal whirlpools of the Naruto Strait and for Awa Odori, Japan's most exuberant summer dance festival. The remote Iya Valley has vine bridges.",
    see:["Naruto whirlpools","Awa Odori (August dance festival)","Iya Valley vine bridges","Mount Tsurugi"],
    eat:"Sudachi citrus and Tokushima ramen.", phrase:P.recommend,
    getting:"Tokushima is reached by bus from Osaka/Kobe over the Akashi-Kaikyō bridge (~2h30m).",
    when:"August 12–15 for Awa Odori; spring tides give the biggest whirlpools.",
    word:{jp:"阿波踊り", ro:"Awa Odori", en:"Tokushima's huge mid-August dance festival"},
    related:["kagawa","kochi"], tip:"The whirlpools are strongest around spring and autumn tides — check the timetable." },
  { slug:"kagawa", kanji:"香川", romaji:"Kagawa", region:"shikoku",
    lede:"Japan's smallest prefecture — udon noodles and art islands.",
    intro:"Kagawa is synonymous with sanuki udon and with the contemporary-art islands of the Seto Inland Sea, anchored by Naoshima.",
    see:["Naoshima and Teshima art islands","Ritsurin Garden","Kotohira-gū (Konpira) shrine","Marugame Castle"],
    eat:"Sanuki udon — chewy, cheap, everywhere.", phrase:P.delicious,
    getting:"Takamatsu is ~50 min from Okayama by train over the Seto-Ōhashi bridge.",
    when:"Spring/summer/autumn for the Setouchi Triennale art festival years.",
    word:{jp:"うどん", ro:"udon", en:"thick wheat noodles — Kagawa is the udon kingdom"},
    related:["okayama","ehime"], tip:"Many Kagawa udon shops are self-serve and open early — a cheap, delicious breakfast." },
  { slug:"ehime", kanji:"愛媛", romaji:"Ehime", region:"shikoku",
    lede:"One of Japan's oldest hot springs and a hilltop castle at Matsuyama.",
    intro:"Ehime's Dōgo Onsen is among the oldest bathhouses in Japan. Matsuyama has a fine original castle, and the Shimanami Kaidō cycling route is world-class.",
    see:["Dōgo Onsen Honkan","Matsuyama Castle","Shimanami Kaidō cycling route","Uchiko's wax-merchant town"],
    eat:"Citrus (mikan) and taimeshi (sea-bream rice).", phrase:P.beautiful,
    getting:"Matsuyama is reached by air from Tokyo/Osaka or by train/bus across Shikoku.",
    when:"Spring–autumn for cycling the Shimanami Kaidō; any season for the onsen.",
    word:{jp:"道後温泉", ro:"Dōgo Onsen", en:"one of Japan's oldest hot-spring bathhouses"},
    related:["kagawa","kochi"], tip:"The Shimanami Kaidō links Ehime to Hiroshima by a chain of bridges — rent a bike one-way." },
  { slug:"kochi", kanji:"高知", romaji:"Kochi", region:"shikoku",
    lede:"A clear river, a famous castle, and the spirit of reformer Sakamoto Ryōma.",
    intro:"Kōchi faces the Pacific on Shikoku's south. It has one of Japan's few original castles, the pristine Shimanto River, and a proud local food culture.",
    see:["Kōchi Castle (original keep)","Shimanto River","Katsurahama beach","Cape Ashizuri"],
    eat:"Katsuo no tataki (seared bonito) is the signature dish.", phrase:P.recommend,
    getting:"Kōchi is reached by air from Tokyo/Osaka or by limited express across Shikoku.",
    when:"Spring–autumn for the Shimanto River; August for the Yosakoi dance festival.",
    word:{jp:"カツオのたたき", ro:"katsuo no tataki", en:"seared bonito, Kōchi's signature dish"},
    related:["ehime","tokushima"], tip:"Try katsuo no tataki seared over rice straw for the most authentic smoky flavour." },

  // ── KYŪSHŪ / OKINAWA ──
  { slug:"fukuoka", kanji:"福岡", romaji:"Fukuoka", region:"kyushu-okinawa",
    lede:"Kyūshū's gateway city, famous for tonkotsu ramen and street-food stalls.",
    intro:"Fukuoka is Kyūshū's largest, friendliest city — close to Korea, packed with riverside yatai food stalls, and a great base for the whole island.",
    see:["Yatai (street-food stalls) along the river","Ōhori Park and ruins of Fukuoka Castle","Dazaifu Tenmangū shrine","Canal City complex"],
    eat:"Hakata tonkotsu ramen and mentaiko (spicy cod roe).", phrase:P.delicious,
    getting:"Fukuoka (Hakata) is ~5h from Tokyo by shinkansen, or ~2h by air.",
    when:"Year-round; the yatai stalls are liveliest on warm evenings.",
    word:{jp:"屋台", ro:"yatai", en:"open-air food stalls — a Fukuoka institution"},
    related:["saga","kumamoto"], tip:"Eat at a riverside yatai in Nakasu at night — point and order; seats are limited." },
  { slug:"saga", kanji:"佐賀", romaji:"Saga", region:"kyushu-okinawa",
    lede:"Japan's porcelain heartland and a vivid autumn balloon festival.",
    intro:"Small Saga is the birthplace of Japanese porcelain — Arita and Imari wares are world-famous — and hosts a spectacular hot-air balloon fiesta each autumn.",
    see:["Arita and Imari porcelain towns","Yoshinogari prehistoric site","Saga International Balloon Fiesta","Yutoku Inari Shrine"],
    eat:"Saga beef and fresh squid in Yobuko.", phrase:P.recommend,
    getting:"Saga is ~40 min from Fukuoka (Hakata) by limited express.",
    when:"Late October–early November for the balloon fiesta.",
    word:{jp:"有田焼", ro:"Arita-yaki", en:"Arita porcelain — among Japan's most famous ceramics"},
    related:["fukuoka","nagasaki"], tip:"Combine Saga with Fukuoka — they're close, and Saga is far less crowded." },
  { slug:"nagasaki", kanji:"長崎", romaji:"Nagasaki", region:"kyushu-okinawa",
    lede:"A port city of cross-cultural history, hillside views, and a peace park.",
    intro:"Nagasaki was Japan's window to the world during its isolation, leaving Dutch, Chinese, and Christian heritage. It also remembers 1945 with its Peace Park.",
    see:["Glover Garden and harbor views","Nagasaki Peace Park","Dejima former Dutch trading post","Gunkanjima (Hashima Island)"],
    eat:"Champon and sara-udon noodles; castella sponge cake.", phrase:P.recommend,
    getting:"Nagasaki is ~1h30m from Fukuoka via the Nishi-Kyūshū Shinkansen + transfer.",
    when:"Any season; the night view from Mount Inasa is famous year-round.",
    word:{jp:"ちゃんぽん", ro:"champon", en:"Nagasaki's hearty mixed noodle dish"},
    related:["saga","kumamoto"], tip:"Mount Inasa's night view is rated among Japan's three best — go up by ropeway after dark." },
  { slug:"kumamoto", kanji:"熊本", romaji:"Kumamoto", region:"kyushu-okinawa",
    lede:"A mighty castle and one of the world's largest volcanic calderas at Aso.",
    intro:"Kumamoto's imposing castle is a symbol of Kyūshū, and Mount Aso's vast caldera is among the largest active volcanic basins on earth.",
    see:["Kumamoto Castle","Mount Aso caldera","Suizenji Jōjuen garden","Kurokawa Onsen"],
    eat:"Basashi (horse sashimi) and Kumamoto ramen.", phrase:P.beautiful,
    getting:"Kumamoto is ~40 min from Fukuoka (Hakata) by Kyūshū Shinkansen.",
    when:"Spring–autumn for Aso (check volcanic activity advisories before going).",
    word:{jp:"火山", ro:"kazan", en:"volcano — Mount Aso is the region's giant"},
    related:["fukuoka","oita"], tip:"Mount Aso access can close on short notice for volcanic gas — check the day's status first." },
  { slug:"oita", kanji:"大分", romaji:"Oita", region:"kyushu-okinawa",
    lede:"Japan's hot-spring capital — steaming Beppu and chic Yufuin.",
    intro:"Ōita produces more hot-spring water than anywhere in Japan. Beppu's 'hells' are vivid coloured springs, while Yufuin is a stylish onsen retreat below a twin-peaked mountain.",
    see:["Beppu's 'Hells' (jigoku) hot springs","Yufuin onsen town","Usuki stone Buddhas","Mount Yufu"],
    eat:"Toriten (chicken tempura) and bungo beef.", phrase:P.beautiful,
    getting:"Beppu/Ōita are ~2h from Fukuoka (Hakata) by limited express.",
    when:"Any season — onsen are wonderful in cooler months.",
    word:{jp:"地獄", ro:"jigoku", en:"the 'hells' — Beppu's vividly coloured hot springs (for viewing)"},
    related:["kumamoto","fukuoka"], tip:"The Beppu 'hells' are for viewing, not bathing — separate onsen are for soaking." },
  { slug:"miyazaki", kanji:"宮崎", romaji:"Miyazaki", region:"kyushu-okinawa",
    lede:"Sunny Pacific coast, surf, and shrines wrapped in myth.",
    intro:"Miyazaki on Kyūshū's southeast coast has a mild, sunny climate, palm-lined drives, and deep ties to Japan's creation myths at Takachiho Gorge.",
    see:["Takachiho Gorge","Udo Shrine in a seaside cave","Aoshima island and shrine","Nichinan coast"],
    eat:"Chicken nanban and Miyazaki mango.", phrase:P.beautiful,
    getting:"Miyazaki is reached by air from major cities, or by limited express within Kyūshū.",
    when:"Summer for surf and mango; any season for the mild coast.",
    word:{jp:"高千穂", ro:"Takachiho", en:"a gorge and mythical site in Japan's creation legends"},
    related:["kagoshima","oita"], tip:"Row a boat into Takachiho Gorge for the classic view of the waterfall up close." },
  { slug:"kagoshima", kanji:"鹿児島", romaji:"Kagoshima", region:"kyushu-okinawa",
    lede:"An active volcano across the bay and a gateway to ancient-forest islands.",
    intro:"Kagoshima sits beneath the smoking Sakurajima volcano, often called the 'Naples of the East'. It's the jumping-off point for the cedar-forest island of Yakushima.",
    see:["Sakurajima volcano","Sengan-en garden","Yakushima ancient cedar forest (UNESCO)","Ibusuki sand baths"],
    eat:"Kurobuta (black pork) and satsuma-age fish cakes.", phrase:P.recommend,
    getting:"Kagoshima is ~1h40m from Fukuoka by Kyūshū Shinkansen, or by air.",
    when:"Spring–autumn for Yakushima hiking; any season for the city and onsen.",
    word:{jp:"桜島", ro:"Sakurajima", en:"the active volcano looming over Kagoshima Bay"},
    related:["miyazaki","kumamoto"], tip:"Try the Ibusuki sand baths — you're buried in naturally hot volcanic sand." },
  { slug:"okinawa", kanji:"沖縄", romaji:"Okinawa", region:"kyushu-okinawa", full:true,
    blurb:"Subtropical islands and distinct Ryukyu culture." },
];
